### ISSUE TITLE
feature_ID instead ENSEMBL ID in .cloupe file

### ISSUE THREAD

**Issue by robingarcia** [10XGenomics/loupeR#17] opened 2023-10-26 07:19 UTC
Hello, 

when I use `create_loupe_from_seurat()` or `create_loupe()` the created `.cloupe` file contains "feature_ID" instead "ENSEMBL IDs". 

What is wrong here?

Lets search for 

- Sox17: [https://www.ensembl.org/Multi/Search/Results?q=feature_6](https://www.ensembl.org/Multi/Search/Results?q=feature_6) --> should be: ENSG00000164736
- Xkr4: [https://www.ensembl.org/Multi/Search/Results?q=feature_1](https://www.ensembl.org/Multi/Search/Results?q=feature_1) --> should be: ENSG00000206579

The "feature_ID" matches with the row number of the dgCMatrix. 

The imported dgCMatrix (outs/filtered_feature_bc_matrix.h5) always contains only gene names or, if no gene name is available, the ENSEMBL ID.
In the `*.gtf` file, the gene names and ENSEBML ID are stored together or the ENSEMBL ID is stored twice if the gene name is missing. 

I am unsure whether this is a bug in the R package `loupeR` or not, since the SeuratObject nor the dgCMatrix does not contain the ENSEMBL ID for each gene name. This would mean that the user has to take care of adjusting the dgCMatrix stored in the SeuratObject himself. 

A solution could be to give the function `create_loupe_from_seurat()` a `*.gtf` file or a two-column `*.csv` file (e.g. read_gtf=), which then replaces the line number (aka feature_ID) for the respective gene names/ENSEMBL-IDs with the ENSEMBL-ID stored in the `*.gtf` file. This will not work from the dgCMatrix alone. 

The `.cloupe` file created by `cellranger count` probably uses information from the `*.gtf` file. 

The data set shown in the screenshot was created according to the 10X tutorial.
[https://www.10xgenomics.com/support/software/loupe-browser/tutorials/lb-louper](https://www.10xgenomics.com/support/software/loupe-browser/tutorials/lb-louper)

I thank you in advance for your support.

![sox17_xkr4](https://github.com/10XGenomics/loupeR/assets/19394603/4b120d79-fc61-4693-bb07-dde24e909e19)

```
> head(test_object@assays$RNA@counts)
6 x 7377 sparse Matrix of class "dgCMatrix"
  [[ suppressing 53 column names ‘AAACCCAAGGCATCAG-1’, ‘AAACCCAAGGTTCACT-1’, ‘AAACCCACAAAGGCTG-1’ ... ]]
                                                                                                                     
Xkr4    3 3 9 12 19 8 2 1 . 5 . . 3 4 4 8 5 6 . 3 2 2 . 25 2 . . 2 . 1 18 8 . . 15 . 8 4 4 1 21 4 1 . 11 3 . 2 . . 18
Gm1992  . . 1  .  . . . . . . . . . 1 . 2 1 . . . . . .  3 . . . . . 4  2 . . .  3 . . . . .  . 1 . .  2 . . . . .  2
Gm19938 . . 3  1  . . . . . 1 . . 2 1 1 . 2 . . 1 . . .  1 . . . 1 . .  1 1 . .  . . . . . 1  1 . . .  1 . . . . 1  1
Gm37381 . . .  .  . . . . . . . . . . . . . . . . . . .  . . . . . . .  . . . .  . . . . . .  . . . .  . . . . . .  .
Rp1     . . .  .  . . . . . . . . . . . . 1 . . . . . .  . . . . . . .  . . . .  . . . . . .  . . . .  . . . . . .  .
Sox17   . . .  .  . . . . . . . . . . . . . . . . . . .  . . . . . . .  . . . .  . . . . . .  . . . .  . . . . . .  .
                   
Xkr4    13 3 ......
Gm1992   . . ......
Gm19938  1 . ......
Gm37381  . . ......
Rp1      . . ......
Sox17    . . ......

 .....suppressing 7324 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................
```

**Comment by robingarcia** [comment] 2023-10-26 07:34
Same issue reported twice. 

See #12

**Comment by esiegel** [comment] 2023-10-26 16:43
Yes, this is indeed a duplicate of the ticket you linked.  Still considering the most ergonomic API for users to include their ensemble ids.  The cellranger data should include these IDs.  When reading the `filtered_feature_bc_matrix` directory, which includes a `features.tsv.gz`, the ensemble ids will be one of the columns.  In the `filtered_feature_bc_matrix.h5` file you can see the ensemble ids with this command `h5dump -d '/matrix/features/id' filtered_feature_bc_matrix.h5` and the feature names with this command `h5dump -d '/matrix/features/name' filtered_feature_bc_matrix.h5`

The core issue is when creating a Seurat object from this data, only the names or ids are selected as the sparse matrix `rownames`.  For the first release of `loupeR` it was important that it was super easy to convert a Seurat object to a loupe file.  Now we need to figure out how to include this data.

**Closed by esiegel** 2023-10-26 16:43 UTC
