### ISSUE TITLE
all values must be less than 32767

### ISSUE THREAD

**Issue by garci1294** [10XGenomics/loupeR#2] opened 2023-09-18 16:53 UTC
Hello,

Thank you for providing this amazing tool. I have a Seurat object with approximately 39,259 cells.

However, I encounter an error when using it. Notably, I don't receive this error with smaller objects. Here's the error message:

```
2023/09/18 11:50:23 Dataset "/clusters/cells/assignments": all values must be less than 32767
Error in create_loupe(assay@counts, clusters = clusters, projections = projections,  :
```
Attached is the bug report:

```
> create_bugreport_from_seurat(seurat_integrated)

Metadata:

tool: loupeR
tool_version: 1.0.0
os: macOS Ventura 13.4
system: aarch64-apple-darwin20 (64-bit)
language: R
language_version: 4.3.1
extra:
     loupeR_seurat_version: 4.9.9.9059
     loupeR_seurat_object_version: 4.1.2
     loupeR_hdf5r_version: 1.3.8
     loupeR_hdf5_version: 1.12.2

Selections:

selected assay:
    RNA
selected clusters:
    active_cluster
    orig.ident
    sample
    DoubletFinder_Ann
    cells
    groupg3v1
    groupg3v2
    groupg4v1
    groupg4v2
    Phase
    mitoFr
    integrated_snn_res.0.4
    integrated_snn_res.0.6
    integrated_snn_res.0.8
    integrated_snn_res.1
    integrated_snn_res.1.2
    integrated_snn_res.1.4
    integrated_snn_res.1.6
    integrated_snn_res.1.8
    integrated_snn_res.2
    integrated_snn_res.2.2
    integrated_snn_res.2.4
    integrated_snn_res.2.6
    integrated_snn_res.2.8
    integrated_snn_res.3
    integrated_snn_res.3.2
    integrated_snn_res.3.4
    integrated_snn_res.3.6
    integrated_snn_res.3.8
    integrated_snn_res.4
    integrated_snn_res.4.2
    integrated_snn_res.4.4
    integrated_snn_res.4.6
    integrated_snn_res.4.8
    integrated_snn_res.5
    integrated_snn_res.5.2
    integrated_snn_res.5.4
    integrated_snn_res.5.6
    integrated_snn_res.5.8
    integrated_snn_res.6
    integrated_snn_res.6.2
    SingleR
    ident_v1
    ident_v2
    ident_v3
    pre.ident
    labeled.ident
selected projections:
    umap

Matrix Sampling:

feature count: 29564
barcode count: 39259
feature sampling:
    AC064852.1
    AC005261.2
    AC133634.1
    LEUTX
    PCDH19
    RAB32
    PPIP5K2
    NXPH2
    IFNE
    CNPY4
barcode sampling:
    Chord101_CCTCCAACAGATCATC-1
    Chord10a_TCACACCTCGCGTGCA-1
    Chord89_CTCATTACAAGACTGG-1
    Chord86b_CCTCTCCTCCAAGCCG-1
    Chord101_CGGGCATAGCCATTTG-1
    Chord101_CCATCACCATGTCAGT-1
    Chord104_TCCACGTCAGATACCT-1
    Chord14a_ATGAGTCGTTGCAAGG-1
    Chord86b_ACTTTCACATAGTCGT-1
    Chord101_TGAGTCACATGGTACT-1

Validation:

    count matrix: (VALID)
    clusters:     (VALID)
    projections:  (VALID)
> 
```

Could you please assist?

Thank you,
Jesus

**Comment by esiegel** [comment] 2023-09-18 19:35
Firstly, thank you for reaching out.   Glad to see this starting to get some traction.

The issue is most likely that you have some cluster that has a unique name for every cell - maybe one of the `ident` clusters.  Internally, the Loupe Browser can supports clusters with a max of 32767 groupings.  The solution here is to remove the unsupported cluster.

Without knowing how you have generated your dataset, via `create_loupe` or `create_loupe_from_seurat`, you can do something like this:

```r
# import the library
library("loupeR")

# Gene Expression RNA assay
assay <- seurat_obj[["RNA"]]

# select clusters and filter those that have too many names/levels
clusters <- select_clusters(seurat_obj)
clusters <- clusters[lapply(clusters, nlevels) < 32767]

# convert the count matrix, clusters, and projections into a Loupe file
create_loupe(
    assay@counts,
    clusters = clusters,
    projections = select_projections(seurat_obj)
)
```

**Comment by esiegel** [comment] 2023-09-20 17:45
@garci1294 any update on this?  Have you tried the above fix?

**Comment by esiegel** [comment] 2023-09-26 17:29
Closing this.  Feel free to open if you are still having issues.

**Closed by esiegel** 2023-09-26 17:29 UTC
Labels: documentation
